#!/bin/tcsh -f
# @MGH1_GROUP Script
# Started Feb.2006, Latest update Feb.2006
# This script is for analyzing data across session
# It assumes that data has ALREADY been converted to MGH1 format
# and that the initial MGH1 (unprocessed data) are all located in the
# same directory.
#
# Furthermore, it assumes that ALL the runs feature the same prefix root.
# For example, let's say Monkey X has three sessions:
# monkX060101, monkX060102, monkX060103
# The root prefix would be monkX0601...
# This allows the program to analyze all runs

echo "**************************************************"
echo "**  @MGH1_Part5 - Multiple Regression Analysis  **"
echo "**      script Ver.1.0 by AHB, Jan 2006         **"
echo "**************************************************"
echo " "
echo "fMRI Parameters"
echo "---------------"
echo " "
echo "TR: "${TR}
echo "Number of sessions: "${nSess}
echo "Max number of runs per session: "${maxR}
echo "Total number of runs: "${nR}
echo " "
echo "Number of timepoints: "${nt}
echo "Number of slices: "${ns}
echo " "
echo "Baseline volume: "${baseline}
echo " "
echo "Output directory: "${out_dir}
echo "Script directory: "${script_dir}
echo "Intermediate directory :"${int_dir}
echo "SUMA directory :"${out_dir}SUMA
echo "ROI directory :"${out_dir}ROI
echo " "
echo " "

#**************** PART FIVE - Multiple Regression Analysis ****************#
part5:

############################################################################
# STEP 12.0 - Multiple regression analysis
############################################################################

step12:
echo "Step 12 - Multiple regression analysis"
date

rm -f ${prefix}_MultiReg* ${prefix}_bucket*

3dDeconvolve -input ${prefix}_AllSessions+orig \
-mask all_mask+orig \
-censor ${script_dir}/all_censor.1D \
-concat ${script_dir}/all_concat.1D \
-polort 2 \
-jobs 6 \
-num_stimts 11 \
-stim_file 1 ${script_dir}/mkface_MION.1D'[1]' -stim_label 1 mkface \
-stim_file 2 ${script_dir}/mkplace_MION.1D'[1]' -stim_label 2 mkplace \
-stim_file 3 ${script_dir}/mkobject_MION.1D'[1]' -stim_label 3 mkobject \
-stim_file 4 ${script_dir}/mkbody_MION.1D'[1]' -stim_label 4 mkbody \
-stim_file 5 ${script_dir}/scrambled_MION.1D'[1]' -stim_label 5 scrambled \
-stim_file 6 ${script_dir}/all_motion.1D'[1]' -stim_label 6 roll -stim_base 6\
-stim_file 7 ${script_dir}/all_motion.1D'[2]' -stim_label 7 pitch -stim_base 7\
-stim_file 8 ${script_dir}/all_motion.1D'[3]' -stim_label 8 yaw -stim_base 8\
-stim_file 9 ${script_dir}/all_motion.1D'[4]' -stim_label 9 dS -stim_base 9\
-stim_file 10 ${script_dir}/all_motion.1D'[5]' -stim_label 10 dL -stim_base 10\
-stim_file 11 ${script_dir}/all_motion.1D'[6]' -stim_label 11 dP -stim_base 11\
-num_glt 28 \
-gltsym 'SYM: +mkface +mkplace +mkobject +mkbody +scrambled' -glt_label 1 all_conds \
-gltsym 'SYM: +mkface -mkplace' -glt_label 2  mkface-mkplace \
-gltsym 'SYM: +mkface -mkobject' -glt_label 3  mkface-mkobject \
-gltsym 'SYM: +mkface -mkbody' -glt_label 4  mkface-mkbody \
-gltsym 'SYM: +mkface -scrambled' -glt_label 5  mkface-scrambled \
-gltsym 'SYM: +mkplace -mkobject' -glt_label 6  mkplace-mkobject \
-gltsym 'SYM: +mkplace -mkbody' -glt_label 7  mkplace-mkbody \
-gltsym 'SYM: +mkplace -scrambled' -glt_label 8  mkplace-scrambled \
-gltsym 'SYM: +mkobject -mkbody' -glt_label 9  mkobject-mkbody \
-gltsym 'SYM: +mkobject -scrambled' -glt_label 10  mkobject-scrambled \
-gltsym 'SYM: +mkbody -scrambled' -glt_label 11  mkbody-scrambled \
-gltsym 'SYM: +mkface +mkface +mkface -mkplace -mkobject -mkbody' -glt_label 12  mkface-allconds \
-gltsym 'SYM: -mkface +mkplace +mkplace +mkplace -mkobject -mkbody' -glt_label 13  mkplace-allconds \
-gltsym 'SYM: -mkface -mkplace +mkobject +mkobject +mkobject -mkbody' -glt_label 14  mkobject-allconds \
-gltsym 'SYM: -mkface -mkplace -mkobject +mkbody +mkbody +mkbody' -glt_label 15  mkbody-allconds \
-gltsym 'SYM: +mkface -mkplace -mkobject -mkbody' -glt_label 16  allface-allconds \
-gltsym 'SYM: -mkface +mkplace -mkobject -mkbody' -glt_label 17  allplace-allconds \
-gltsym 'SYM: +mkface -scrambled \ +mkplace -scrambled \ +mkobject -scrambled \ +mkbody -scrambled' -glt_label 18  allconds-scrambled_corr \
-gltsym 'SYM: +mkface +mkplace +mkobject +mkbody -scrambled' -glt_label 19  allconds-scrambled \
-gltsym 'SYM: +mkface +mkbody -mkplace -mkobject' -glt_label 20 ani-inani \
-gltsym 'SYM: +mkface -mkplace \ +mkface -mkobject' -glt_label 21 face-inanimate \
-gltsym 'SYM: +mkbody -mkplace \ +mkbody -mkobject' -glt_label 22 body-inanimate \
-gltsym 'SYM: +mkplace -mkface \ +mkplace -mkbody' -glt_label 23 place-animate \
-gltsym 'SYM: +mkobject -mkface \ +mkobject -mkbody' -glt_label 24 object-animate \
-gltsym 'SYM: +mkface -mkplace \ +mkface -mkobject \ +mkface -mkbody' -glt_label 25  face-all_corr \
-gltsym 'SYM: +mkplace -mkface \ +mkplace -mkobject \ +mkplace -mkbody' -glt_label 26  place-all_corr \
-gltsym 'SYM: +mkobject -mkface \ +mkobject -mkplace \ +mkobject -mkbody' -glt_label 27  object-all_corr \
-gltsym 'SYM: +mkbody -mkface \ +mkbody -mkobject \ +mkbody -mkplace' -glt_label 28  bodyp-all_corr \
-fitts ${prefix}_MultiReg -fout -tout -full_first -nobout -bucket ${prefix}_bucket

date
echo "Done Part 5 - " ${prefix}|mail -s "MGH1_Script Part 5 - Completed" ${email}
goto exit


exit:

