#!/bin/tcsh
# @FixOrient
# by AHB, started March 2012
# Version 1.0
# Script to fix orientation of files/masks analysed by MNoonan (i.e., orientation correction left until the end)

if ($#argv < 2) then
	echo " "
	echo "*******************************"
	echo "@FixOrient by AHB, V.03.22.2012"
	echo "*******************************"
	echo " "
	echo "Script to correct orientation of files obtained from Rushworth group (who correct"
	echo "orientation at a different stage."
	echo " "
	echo "INPUT: @FixOrient <INPUT_FILE> <OUTPUT_FILE>"
	echo " "
	goto exit
endif

set in = $1
set out = $2

fslswapdim $in -x z y temp1
fslorient -deleteorient temp1.nii.gz
fslorient -setqformcode 1 temp1.nii.gz
		
fslswapdim temp1.nii.gz x z y $out
fslorient -deleteorient $out.nii.gz 
fslorient -setqformcode 1 $out.nii.gz 
rm temp1.nii.gz