#!/bin/sh

#   tbss_monkey_1_preproc - preprocess FA data for TBSS
#
#   Stephen Smith, FMRIB Image Analysis Group
#	Later modified and ruined by Andrew Bell, Oxford#

export LC_ALL=C

Usage() {
    echo ""
    echo "Usage: tbss_monkey_1_preproc <image1> <image2> ..."
    echo ""
    exit 1
}

[ "$1" = "" ] && Usage

echo [`date`] [`hostname`] [`uname -a`] [`pwd`] [$0 $@] >> .tbsslog

mkdir -p FA
mkdir -p origdata

for f in `$FSLDIR/bin/imglob $@` ; do

    echo processing $f

    # erode a little and zero end slices
    X=`${FSLDIR}/bin/fslval $f dim1`; X=`echo "$X 2 - p" | dc -`
    Y=`${FSLDIR}/bin/fslval $f dim2`; Y=`echo "$Y 2 - p" | dc -`
    Z=`${FSLDIR}/bin/fslval $f dim3`; Z=`echo "$Z 2 - p" | dc -`
    $FSLDIR/bin/fslmaths $f -min 1 -ero -roi 1 $X 1 $Y 1 $Z 0 1 FA/${f}_FA

    # create mask (for use in FLIRT & FNIRT)
    $FSLDIR/bin/fslmaths FA/${f}_FA -bin FA/${f}_FA_mask

    $FSLDIR/bin/fslmaths FA/${f}_FA_mask -dilD -dilD -sub 1 -abs -add FA/${f}_FA_mask FA/${f}_FA_mask -odt char

    $FSLDIR/bin/immv $f origdata
	
done

echo "Now running \"slicesdir\" to generate report of all input images"
cd FA
$FSLDIR/bin/slicesdir `$FSLDIR/bin/imglob *_FA.*` > grot 2>&1
cat grot | tail -n 2
/bin/rm grot

